### ISSUE TITLE
Editing the book details is not completely intuitive 

### ISSUE THREAD

**Issue by spencermg3** [dletk/BookIt#15]
It would be more intuitive if the keyboard would pop up when they hit "edit" and disappears when they hit "save"

**Comment by dletk** [comment]
I like this idea, since all of our textFields are above the keyboard, pop it up directly will not influence the user, and may make them do things faster actually. I will work on implementing this one when you guys are doing the user testing, so you can try it on somebody to see the different reactions.

**Comment by dletk** [comment]
I have made the change in the newest code. Please tested it and tell me what is the feedback.

**Comment by spencermg3** [comment]
Issue has been fixed
