### ISSUE TITLE
App crashes if you enter an extremely large number for the current page from the reading books tab

### ISSUE THREAD

**Issue by spencermg3** [dletk/BookIt#24]
If you do it from the Book Details page then it just resets to zero. But if you do it directly from the reading books tab then it will crash and be zero when you re-open the app

**Comment by dletk** [comment]
Maybe Swift is using 64 bit Int, this will have the maximum value to be 2^63-1, which is about 9.223372037E18, so if you enter 19 number 9s, the app will crash because  overflow creates a nil value when we try to unwrap it. My approach for fixing this bug is assign 0 for the value of current book if the number is overflown

**Comment by dletk** [comment]
Solved!
